#pragma once

// ---------------------------------------------------------------------------
// Expr.h — Expression tree for the PhiX DSL (Stage 1 of DSL refactor).
//
// Design goals
// ------------
// 1. Pure data description — nodes carry no std::function launchers.
//    Launchers are generated by the lowering pass (EvalPlan).
// 2. ghostRequired() is inferred from the tree so Equation::setRHS can
//    validate that every source field has enough ghost cells.
// 3. Constant folding at construction time eliminates the dual s*Field /
//    s*Term scalar-multiply paths (P5 from the design doc).
// 4. The tree categorises nodes as Local (pointwise, no halo) or Stencil
//    (needs halo) — the lowering boundary used in Stage 2.
//
// Relationship to existing Term / RHSExpr
// ----------------------------------------
// Stage 1: Expr is built alongside Term/RHSExpr.  Equation::setRHS gains
//          an Expr overload that builds the tree, runs ghostRequired() checks,
//          then converts back to RHSExpr for actual evaluation.
// Stage 2: The lowering pass replaces the RHSExpr round-trip with a proper
//          EvalPlan that fuses Local subtrees into single kernels.
//
// Node summary
// ------------
//   ExprLeaf           — wraps a const ScalarField* (terminal)
//   ExprScalar         — compile-time constant  (terminal)
//   ExprPointwise1     — Local unary  functor(child)
//   ExprPointwise2     — Local binary functor(left, right)
//   ExprPointwise3     — Local ternary functor(a, b, c)
//   ExprAdd            — Local sum of two sub-expressions
//   ExprMul            — Local product of two sub-expressions
//   ExprScale          — Local constant scale of one sub-expression
//   ExprNeg            — Local negation
//   ExprStencil        — Stencil node: LAP / GRAD / ISO_GRAD
//   ExprStencilBinary  — Stencil node: GRAD_DOT
//
// All nodes are heap-allocated and owned through std::shared_ptr so the
// tree can be freely copied and composed.
// ---------------------------------------------------------------------------

#include "core/Check.h"
#include "field/ScalarField.h"

#define PHIX_FN [=] __host__ __device__

#include <cstddef>
#include <functional>
#include <memory>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <vector>

namespace PhiX {

// ===========================================================================
// StencilKind — tag for Stencil / StencilBinary nodes
// ===========================================================================
enum class StencilKind {
    LAP,       // ∇²
    GRAD,      // d/dx_axis   (2nd-order central FD)
    ISO_GRAD,  // 9-point isotropic gradient component
    GRAD_DOT,  // ∇f · ∇g  (binary)
    DIV,       // ∇ · v  (reserved for vector; unused in Stage 1)
};

// ===========================================================================
// ExprNode — abstract base
// ===========================================================================
struct ExprNode {
    virtual ~ExprNode() = default;

    // -------------------------------------------------------------------------
    // ghostRequired():
    //   Returns the number of ghost layers this subtree requires from the
    //   *source fields*.  For Stencil nodes the child's ghost requirement
    //   resets to zero at the physical materialization boundary, but the
    //   Stencil node itself still requires 1 (or more) halo layers from the
    //   buffer it reads.  We fold both into a single integer:
    //   — Local nodes:   max(children.ghostRequired())
    //   — Stencil nodes: stencilWidth   (the child's requirement is satisfied
    //                    by the materialization step, not visible to the parent)
    // -------------------------------------------------------------------------
    virtual int ghostRequired() const = 0;

    // Returns true if this is a Local (pointwise) node — no stencil access.
    virtual bool isLocal() const = 0;

    // A representative ScalarField for mesh/ghost layout queries.
    // Returns nullptr for pure-scalar subtrees.
    virtual const ScalarField* repField() const = 0;
};

using ExprPtr = std::shared_ptr<ExprNode>;

// ===========================================================================
// Leaf node — one ScalarField
// ===========================================================================
struct ExprLeaf : ExprNode {
    const ScalarField* field;
    explicit ExprLeaf(const ScalarField& f) : field(&f) {}

    int                ghostRequired() const override { return 0; }
    bool               isLocal()       const override { return true; }
    const ScalarField* repField()      const override { return field; }
};

// ===========================================================================
// Constant-scalar node
// ===========================================================================
struct ExprScalar : ExprNode {
    double value;
    explicit ExprScalar(double v) : value(v) {}

    int                ghostRequired() const override { return 0; }
    bool               isLocal()       const override { return true; }
    const ScalarField* repField()      const override { return nullptr; }
};

// ===========================================================================
// Scale node — coeff * child
// Constant folding: if child is also ExprScale, multiply coefficients.
// ===========================================================================
struct ExprScale : ExprNode {
    double   coeff;
    ExprPtr  child;

    ExprScale(double c, ExprPtr ch) : coeff(c), child(std::move(ch)) {}

    int ghostRequired() const override { return child->ghostRequired(); }
    bool isLocal()      const override { return child->isLocal(); }
    const ScalarField* repField() const override { return child->repField(); }
};

// ===========================================================================
// Binary addition — left + right
// ===========================================================================
struct ExprAdd : ExprNode {
    ExprPtr left, right;

    ExprAdd(ExprPtr l, ExprPtr r) : left(std::move(l)), right(std::move(r)) {}

    int ghostRequired() const override {
        return std::max(left->ghostRequired(), right->ghostRequired());
    }
    bool isLocal() const override {
        return left->isLocal() && right->isLocal();
    }
    const ScalarField* repField() const override {
        if (auto* f = left->repField())  return f;
        return right->repField();
    }
};

// ===========================================================================
// Binary multiplication (Hadamard) — left * right
// ===========================================================================
struct ExprMul : ExprNode {
    ExprPtr left, right;

    ExprMul(ExprPtr l, ExprPtr r) : left(std::move(l)), right(std::move(r)) {}

    int ghostRequired() const override {
        return std::max(left->ghostRequired(), right->ghostRequired());
    }
    bool isLocal() const override {
        return left->isLocal() && right->isLocal();
    }
    const ScalarField* repField() const override {
        if (auto* f = left->repField())  return f;
        return right->repField();
    }
};

// ===========================================================================
// Negation — -child
// ===========================================================================
struct ExprNeg : ExprNode {
    ExprPtr child;
    explicit ExprNeg(ExprPtr ch) : child(std::move(ch)) {}

    int ghostRequired() const override { return child->ghostRequired(); }
    bool isLocal()      const override { return child->isLocal(); }
    const ScalarField* repField() const override { return child->repField(); }
};

// ===========================================================================
// Pointwise nodes — user-supplied functors
// All are Local: ghostRequired() = max(children)
// ===========================================================================

// Unary: f(child)
struct ExprPointwise1 : ExprNode {
    ExprPtr child;
    // Functor stored type-erased (CPU+GPU paths handled at lowering time).
    // For Stage 1 we store the original pw() Term for round-trip compatibility.
    // The functor itself is embedded in the Term captured below.
    //
    // Invariant: pwTerm.type == TermType::POINTWISE  (or COMPOSITE for 2-3 field pw)
    // This is set when constructing via make_pw1/2/3 helpers.

    ExprPtr child2;  // nullptr for unary
    ExprPtr child3;  // nullptr for unary / binary

    // The prebuilt Term is carried so Stage 1 evaluation can delegate to it
    // while Stage 2 lowering replaces it with a fused kernel.
    // Use a shared_ptr to keep Term copyable.
    std::shared_ptr<struct TermCapture> termCapture;

    ExprPointwise1() = default;

    int ghostRequired() const override {
        int g = child ? child->ghostRequired() : 0;
        if (child2) g = std::max(g, child2->ghostRequired());
        if (child3) g = std::max(g, child3->ghostRequired());
        return g;
    }
    bool isLocal() const override { return true; }
    const ScalarField* repField() const override {
        if (child)  if (auto* f = child->repField())  return f;
        if (child2) if (auto* f = child2->repField()) return f;
        if (child3) if (auto* f = child3->repField()) return f;
        return nullptr;
    }
};

// ===========================================================================
// Stencil node — needs ghost cells
//
// ghostRequired() returns stencilWidth (1 for CD2 / iso9; 2 for 4th-order).
// The child sub-tree will be materialized before the stencil is applied, so
// the child's ghostRequired() is NOT propagated upward from this node.
// ===========================================================================
struct ExprStencil : ExprNode {
    StencilKind kind;
    int         axis;         // relevant for GRAD / ISO_GRAD
    int         stencilWidth; // halo cells required (1 for CD2)
    ExprPtr     child;
    std::string schemeName;
    std::string selection;

    ExprStencil(StencilKind k, int ax, int sw, ExprPtr ch)
        : kind(k), axis(ax), stencilWidth(sw), child(std::move(ch)) {}

    int ghostRequired() const override { return stencilWidth; }
    bool isLocal()      const override { return false; }
    const ScalarField* repField() const override { return child->repField(); }
};

// ===========================================================================
// Binary stencil — GRAD_DOT: ∇f · ∇g
// Both inputs are ScalarField leaves (no nested expression support yet).
// ===========================================================================
struct ExprStencilBinary : ExprNode {
    StencilKind kind;
    int         stencilWidth;
    ExprPtr     left, right;

    ExprStencilBinary(StencilKind k, int sw, ExprPtr l, ExprPtr r)
        : kind(k), stencilWidth(sw), left(std::move(l)), right(std::move(r)) {}

    int ghostRequired() const override { return stencilWidth; }
    bool isLocal()      const override { return false; }
    const ScalarField* repField() const override {
        if (auto* f = left->repField())  return f;
        return right->repField();
    }
};

// ===========================================================================
// ExprTree — thin wrapper around ExprPtr for user-facing composition API
// ===========================================================================

// Combining two subtrees whose representative fields live on different mesh
// geometry (or ghost) would lower into a single kernel using ONE field's
// strides — reject at composition time.
inline void checkExprMeshMatch(const ExprPtr& l, const ExprPtr& r,
                               const char* who) {
    const ScalarField* a = l ? l->repField() : nullptr;
    const ScalarField* b = r ? r->repField() : nullptr;
    if (a && b && (!check::sameMeshGeometry(a->mesh, b->mesh)
                   || a->ghost != b->ghost))
        throw ValidationError(who,
            "operands reference fields '" + a->name + "' and '" + b->name
            + "' with different mesh geometry or ghost width",
            "build all fields entering one expression from the same Mesh "
            "object with the same ghost");
}

struct ExprTree {
    ExprPtr node;

    ExprTree() = default;
    explicit ExprTree(ExprPtr n) : node(std::move(n)) {}

    // Implicit construction from ScalarField
    ExprTree(const ScalarField& f)
        : node(std::make_shared<ExprLeaf>(f)) {}

    bool empty() const { return !node; }

    int ghostRequired() const { return node ? node->ghostRequired() : 0; }
    bool isLocal()      const { return node ? node->isLocal()       : true; }
    const ScalarField* repField() const {
        return node ? node->repField() : nullptr;
    }

    // -----------------------------------------------------------------------
    // Arithmetic operators — produce a new ExprTree without modifying inputs
    // -----------------------------------------------------------------------
    ExprTree operator+(const ExprTree& rhs) const {
        checkExprMeshMatch(node, rhs.node, "ExprTree::operator+");
        return ExprTree(std::make_shared<ExprAdd>(node, rhs.node));
    }
    ExprTree operator-(const ExprTree& rhs) const {
        // a - b  ==  a + (-1 * b)
        checkExprMeshMatch(node, rhs.node, "ExprTree::operator-");
        return ExprTree(std::make_shared<ExprAdd>(
            node,
            std::make_shared<ExprScale>(-1.0, rhs.node)));
    }
    ExprTree operator*(const ExprTree& rhs) const {
        checkExprMeshMatch(node, rhs.node, "ExprTree::operator*");
        return ExprTree(std::make_shared<ExprMul>(node, rhs.node));
    }
    ExprTree operator*(double s) const {
        // Constant folding: if child is ExprScale, merge coefficients
        if (auto* sc = dynamic_cast<ExprScale*>(node.get()))
            return ExprTree(std::make_shared<ExprScale>(sc->coeff * s, sc->child));
        return ExprTree(std::make_shared<ExprScale>(s, node));
    }
    ExprTree operator/(double s) const { return *this * (1.0 / s); }
    ExprTree operator-() const {
        return ExprTree(std::make_shared<ExprScale>(-1.0, node));
    }

    ExprTree& operator+=(const ExprTree& rhs) { *this = *this + rhs; return *this; }
    ExprTree& operator-=(const ExprTree& rhs) { *this = *this - rhs; return *this; }
};

inline ExprTree operator*(double s, const ExprTree& e)  { return e * s; }
inline ExprTree operator+(double s, const ExprTree& e)  {
    return ExprTree(std::make_shared<ExprAdd>(
        std::make_shared<ExprScalar>(s), e.node));
}
inline ExprTree operator-(double s, const ExprTree& e)  {
    return ExprTree(std::make_shared<ExprAdd>(
        std::make_shared<ExprScalar>(s),
        std::make_shared<ExprScale>(-1.0, e.node)));
}
inline ExprTree operator+(const ExprTree& e, double s)  {
    return ExprTree(std::make_shared<ExprAdd>(
        e.node, std::make_shared<ExprScalar>(s)));
}
inline ExprTree operator-(const ExprTree& e, double s)  {
    return ExprTree(std::make_shared<ExprAdd>(
        e.node, std::make_shared<ExprScalar>(-s)));
}

// ===========================================================================
// Ghost-requirement validation
//
// Walks the ExprTree and verifies that every ScalarField leaf has at least
// as many ghost cells as required by its context.  Call from
// Equation::setRHS after building the tree.
//
// Throws std::invalid_argument with a descriptive message on failure.
// ===========================================================================
inline void validateGhostRequirements(const ExprTree& tree) {
    // Simple recursive check: visit each leaf and verify ghost >= required
    // at that leaf's context.  We report the whole-tree max requirement as
    // the message (exact per-leaf context tracking is a Stage 2 concern).
    int required = tree.ghostRequired();
    if (required <= 0) return;  // no stencil nodes → nothing to check

    std::function<void(const ExprNode*, int)> visit =
        [&](const ExprNode* n, int ctx_required) {
            if (!n) return;
            if (auto* leaf = dynamic_cast<const ExprLeaf*>(n)) {
                if (leaf->field && leaf->field->ghost < ctx_required) {
                    throw std::invalid_argument(
                        std::string("ExprTree ghost validation: field '")
                        + leaf->field->name + "' has ghost="
                        + std::to_string(leaf->field->ghost)
                        + " but the expression requires "
                        + std::to_string(ctx_required));
                }
            } else if (auto* sc = dynamic_cast<const ExprScale*>(n)) {
                visit(sc->child.get(), ctx_required);
            } else if (auto* add = dynamic_cast<const ExprAdd*>(n)) {
                visit(add->left.get(), ctx_required);
                visit(add->right.get(), ctx_required);
            } else if (auto* mul = dynamic_cast<const ExprMul*>(n)) {
                visit(mul->left.get(), ctx_required);
                visit(mul->right.get(), ctx_required);
            } else if (auto* neg = dynamic_cast<const ExprNeg*>(n)) {
                visit(neg->child.get(), ctx_required);
            } else if (auto* pw = dynamic_cast<const ExprPointwise1*>(n)) {
                visit(pw->child.get(),  ctx_required);
                if (pw->child2) visit(pw->child2.get(), ctx_required);
                if (pw->child3) visit(pw->child3.get(), ctx_required);
            } else if (auto* st = dynamic_cast<const ExprStencil*>(n)) {
                // The child will be materialized — reset ctx to 0 (the
                // materialized buffer will have the required ghost applied).
                // But the child leaves must have ghost >= stencilWidth.
                visit(st->child.get(), st->stencilWidth);
            } else if (auto* sb = dynamic_cast<const ExprStencilBinary*>(n)) {
                visit(sb->left.get(),  sb->stencilWidth);
                visit(sb->right.get(), sb->stencilWidth);
            }
        };

    visit(tree.node.get(), 0);
}

// ===========================================================================
// Expr operator factories — mirror the Term-based API
//
// These return ExprTree objects.  At Stage 1 each factory also embeds the
// prebuilt Term (via TermCapture) so that Equation::setRHS can fall back to
// the existing launcher-based evaluation path without reimplementing kernels.
// ===========================================================================

// Forward declarations (factories are defined in Expr.inl / Equation.cu)
ExprTree expr_lap  (const ScalarField& f, double coeff = 1.0);
ExprTree expr_grad (const ScalarField& f, int axis, double coeff = 1.0);
ExprTree expr_iso_grad(const ScalarField& f, int axis, double coeff = 1.0);
ExprTree expr_grad_dot(const ScalarField& f, const ScalarField& g, double coeff = 1.0);

class Schemes;
ExprTree expr_lap(const ScalarField &, const Schemes &, double coeff = 1);
ExprTree expr_grad(const ScalarField &, int axis, const Schemes &, double coeff = 1);

// Pointwise factory helpers — wrap pw() lambdas into ExprPointwise1 nodes.
// The actual pw() Term factories are declared in Term.h; these are thin
// wrappers that additionally build the Expr subtree for the new pipeline.

// 1-field pointwise
template<typename Functor>
ExprTree expr_pw(const ScalarField& f, Functor func, double coeff = 1.0);

// 2-field pointwise
template<typename Functor>
ExprTree expr_pw(const ScalarField& f1, const ScalarField& f2,
                 Functor func, double coeff = 1.0);

// 3-field pointwise
template<typename Functor>
ExprTree expr_pw(const ScalarField& f1, const ScalarField& f2,
                 const ScalarField& f3,
                 Functor func, double coeff = 1.0);

} // namespace PhiX

#ifdef __CUDACC__
#include "equation/ExprPW.inl"
#endif
