add_subdirectory(core)
add_subdirectory(mesh)
add_subdirectory(meshmap)
add_subdirectory(boundary)
add_subdirectory(field)
add_subdirectory(scheme)
add_subdirectory(operators)
add_subdirectory(equation)
add_subdirectory(material)
add_subdirectory(perf)
add_subdirectory(solver)
add_subdirectory(lbm)
add_subdirectory(diagnostics)
add_subdirectory(mechanics)
add_subdirectory(IO)

add_subdirectory(numerics)
