# ---------------------------------------------------------------------------
# PhixVersion.cmake — script mode (cmake -P): (re)generate phix_version.h.
#
# Inputs (passed with -D):
#   PHIX_SOURCE_DIR   repo root (changelog/ and .git live here)
#   PHIX_VERSION_OUT  header file to generate
#
# The suite version is the newest changelog/v<X.Y.Z> directory — the same
# source of truth as etc/bashrc's phixVersion.  The git SHA gets a "-dirty"
# suffix when tracked files carry uncommitted changes (untracked files do
# not count).  The header is only rewritten when its content changes, so an
# unchanged stamp costs no recompilation on incremental builds.
# ---------------------------------------------------------------------------

set(version "unknown")
file(GLOB _dirs RELATIVE "${PHIX_SOURCE_DIR}/changelog"
     "${PHIX_SOURCE_DIR}/changelog/v*")
foreach(_d IN LISTS _dirs)
    string(REGEX REPLACE "^v" "" _v "${_d}")
    if(version STREQUAL "unknown" OR _v VERSION_GREATER version)
        set(version "${_v}")
    endif()
endforeach()
if(version STREQUAL "unknown")
    set(version "3.14.0")   # public snapshot ships no changelog/ directory
endif()
set(version "v${version}")

set(sha "unknown")
execute_process(COMMAND git rev-parse --short HEAD
                WORKING_DIRECTORY "${PHIX_SOURCE_DIR}"
                OUTPUT_VARIABLE _sha RESULT_VARIABLE _rc
                OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
if(_rc EQUAL 0)
    set(sha "${_sha}")
    execute_process(COMMAND git status --porcelain -uno
                    WORKING_DIRECTORY "${PHIX_SOURCE_DIR}"
                    OUTPUT_VARIABLE _st RESULT_VARIABLE _strc ERROR_QUIET)
    if(_strc EQUAL 0 AND NOT _st STREQUAL "")
        set(sha "${sha}-dirty")
    endif()
endif()

set(content "// Auto-generated by cmake/PhixVersion.cmake — do not edit.
#pragma once
#define PHIX_VERSION_STRING \"${version}\"
#define PHIX_GIT_SHA \"${sha}\"
")

set(_old "")
if(EXISTS "${PHIX_VERSION_OUT}")
    file(READ "${PHIX_VERSION_OUT}" _old)
endif()
if(NOT content STREQUAL _old)
    file(WRITE "${PHIX_VERSION_OUT}" "${content}")
endif()
